apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
type: Opaque
data:
  # Base64 String:  estoEsMiSecretDeK8s = ZXN0b0VzTWlTZWNyZXREZUs4cw==
  # echo -n postgres | base64
  JWT_SECRET: ZXN0b0VzTWlTZWNyZXREZUs4cw==